REGIONS: dict[str, dict[str, str]] = {
    "arica-y-parinacota": {
        "Arica": "arica",
        "Camarones": "camarones",
        "Putre": "putre",
        "General Lagos": "general-lagos",
    },
    "tarapaca": {
        "Iquique": "iquique",
        "Alto Hospicio": "alto-hospicio",
        "Pozo Almonte": "pozo-almonte",
        "Camiña": "camina",
        "Colchane": "colchane",
        "Huara": "huara",
        "Pica": "pica",
    },
    "antofagasta": {
        "Antofagasta": "antofagasta",
        "Mejillones": "mejillones",
        "Sierra Gorda": "sierra-gorda",
        "Taltal": "taltal",
        "Calama": "calama",
        "Ollagüe": "ollague",
        "San Pedro de Atacama": "san-pedro-de-atacama",
        "Tocopilla": "tocopilla",
        "María Elena": "maria-elena",
    },
    "atacama": {
        "Copiapó": "copiapo",
        "Caldera": "caldera",
        "Tierra Amarilla": "tierra-amarilla",
        "Chañaral": "chanaral",
        "Diego de Almagro": "diego-de-almagro",
        "Vallenar": "vallenar",
        "Alto del Carmen": "alto-del-carmen",
        "Freirina": "freirina",
        "Huasco": "huasco",
    },
    "coquimbo": {
        "La Serena": "la-serena",
        "Coquimbo": "coquimbo",
        "Andacollo": "andacollo",
        "La Higuera": "la-higuera",
        "Paiguano": "paiguano",
        "Vicuña": "vicuna",
        "Illapel": "illapel",
        "Canela": "canela",
        "Los Vilos": "los-vilos",
        "Salamanca": "salamanca",
        "Ovalle": "ovalle",
        "Combarbalá": "combarbala",
        "Monte Patria": "monte-patria",
        "Punitaqui": "punitaqui",
        "Río Hurtado": "rio-hurtado",
    },
    "valparaiso": {
        "Valparaíso": "valparaiso",
        "Casablanca": "casablanca",
        "Concón": "concon",
        "Juan Fernández": "juan-fernandez",
        "Puchuncaví": "puchuncavi",
        "Quintero": "quintero",
        "Viña del Mar": "vina-del-mar",
        "Isla de Pascua": "isla-de-pascua",
        "Los Andes": "los-andes",
        "Calle Larga": "calle-larga",
        "Rinconada": "rinconada",
        "San Esteban": "san-esteban",
        "La Ligua": "la-ligua",
        "Cabildo": "cabildo",
        "Papudo": "papudo",
        "Petorca": "petorca",
        "Zapallar": "zapallar",
        "Quillota": "quillota",
        "Calera": "calera",
        "Hijuelas": "hijuelas",
        "La Cruz": "la-cruz",
        "Nogales": "nogales",
        "San Antonio": "san-antonio",
        "Algarrobo": "algarrobo",
        "Cartagena": "cartagena",
        "El Quisco": "el-quisco",
        "El Tabo": "el-tabo",
        "Santo Domingo": "santo-domingo",
        "San Felipe": "san-felipe",
        "Catemu": "catemu",
        "Llaillay": "llaillay",
        "Panquehue": "panquehue",
        "Putaendo": "putaendo",
        "Santa María": "santa-maria",
        "Limache": "limache",
        "Quilpué": "quilpue",
        "Villa Alemana": "villa-alemana",
        "Olmué": "olmue",
    },
    "bernardo-ohiggins": {
        "Rancagua": "rancagua",
        "Codegua": "codegua",
        "Coinco": "coinco",
        "Coltauco": "coltauco",
        "Doñihue": "donihue",
        "Graneros": "graneros",
        "Las Cabras": "las-cabras",
        "Machalí": "machali",
        "Malloa": "malloa",
        "Mostazal": "mostazal",
        "Olivar": "olivar",
        "Peumo": "peumo",
        "Pichidegua": "pichidegua",
        "Quinta de Tilcoco": "quinta-de-tilcoco",
        "Rengo": "rengo",
        "Requínoa": "requinoa",
        "San Vicente": "san-vicente",
        "Pichilemu": "pichilemu",
        "La Estrella": "la-estrella",
        "Litueche": "litueche",
        "Marchihue": "marchihue",
        "Navidad": "navidad",
        "Paredones": "paredones",
        "San Fernando": "san-fernando",
        "Chépica": "chepica",
        "Chimbarongo": "chimbarongo",
        "Lolol": "lolol",
        "Nancagua": "nancagua",
        "Palmilla": "palmilla",
        "Peralillo": "peralillo",
        "Placilla": "placilla",
        "Pumanque": "pumanque",
        "Santa Cruz": "santa-cruz",
    },
    "maule": {
        "Talca": "talca",
        "Constitución": "constitucion",
        "Curepto": "curepto",
        "Empedrado": "empedrado",
        "Maule": "maule",
        "Pelarco": "pelarco",
        "Pencahue": "pencahue",
        "Río Claro": "rio-claro",
        "San Clemente": "san-clemente",
        "San Rafael": "san-rafael",
        "Cauquenes": "cauquenes",
        "Chanco": "chanco",
        "Pelluhue": "pelluhue",
        "Curicó": "curico",
        "Hualañé": "hualane",
        "Licantén": "licanten",
        "Molina": "molina",
        "Rauco": "rauco",
        "Romeral": "romeral",
        "Sagrada Familia": "sagrada-familia",
        "Teno": "teno",
        "Vichuquén": "vichiquen",
        "Linares": "linares",
        "Colbún": "colbun",
        "Longaví": "longavi",
        "Parral": "parral",
        "Retiro": "retiro",
        "San Javier": "san-javier",
        "Villa Alegre": "villa-alegre",
        "Yerbas Buenas": "yerbas-buenas",
    },
    "biobio": {
        "Concepción": "concepcion",
        "Coronel": "coronel",
        "Chiguayante": "chiguayante",
        "Florida": "florida",
        "Hualqui": "hualqui",
        "Lota": "lota",
        "Penco": "penco",
        "San Pedro de la Paz": "san-pedro-de-la-paz",
        "Santa Juana": "santa-juana",
        "Talcahuano": "talcahuano",
        "Tomé": "tome",
        "Hualpén": "hualpen",
        "Lebu": "lebu",
        "Arauco": "arauco",
        "Cañete": "canete",
        "Contulmo": "contulmo",
        "Curanilahue": "curanilahue",
        "Los Álamos": "los-alamos",
        "Tirúa": "tirua",
        "Los Ángeles": "los-angeles",
        "Antuco": "antuco",
        "Cabrero": "cabrero",
        "Laja": "laja",
        "Mulchén": "mulchen",
        "Nacimiento": "nacimiento",
        "Negrete": "negrete",
        "Quilaco": "quilaco",
        "Quilleco": "quilleco",
        "San Rosendo": "san-rosendo",
        "Santa Bárbara": "santa-barbara",
        "Tucapel": "tucapel",
        "Yumbel": "yumbel",
        "Alto Biobío": "alto-biobio",
    },
    "la-araucania": {
        "Temuco": "temuco",
        "Carahue": "carahue",
        "Cunco": "cunco",
        "Curarrehue": "curarrehue",
        "Freire": "freire",
        "Galvarino": "galvarino",
        "Gorbea": "gorbea",
        "Lautaro": "lautaro",
        "Loncoche": "loncoche",
        "Melipeuco": "melipeuco",
        "Nueva Imperial": "nueva-imperial",
        "Padre Las Casas": "padre-las-casas",
        "Perquenco": "perquenco",
        "Pitrufquén": "pitrufquen",
        "Pucón": "pucon",
        "Saavedra": "saavedra",
        "Teodoro Schmidt": "teodoro-schmidt",
        "Toltén": "tolten",
        "Vilcún": "vilcun",
        "Villarrica": "villarrica",
        "Cholchol": "cholchol",
        "Angol": "angol",
        "Collipulli": "collipulli",
        "Curacautín": "curacautin",
        "Ercilla": "ercilla",
        "Lonquimay": "lonquimay",
        "Los Sauces": "los-sauces",
        "Lumaco": "lumaco",
        "Purén": "puren",
        "Renaico": "renaico",
        "Traiguén": "traiguen",
        "Victoria": "victoria",
    },
    "de-los-rios": {
        "Valdivia": "valdivia",
        "Corral": "corral",
        "Lanco": "lanco",
        "Los Lagos": "los-lagos",
        "Máfil": "mafil",
        "Mariquina": "mariquina",
        "Paillaco": "paillaco",
        "Panguipulli": "panguipulli",
        "La Unión": "la-union",
        "Futrono": "futrono",
        "Lago Ranco": "lago-ranco",
        "Río Bueno": "rio-bueno",
    },
    "los-lagos": {
        "Puerto Montt": "puerto-montt",
        "Calbuco": "calbuco",
        "Cochamó": "cochamo",
        "Fresia": "fresia",
        "Frutillar": "frutillar",
        "Los Muermos": "los-muermos",
        "Llanquihue": "llanquihue",
        "Maullín": "maullin",
        "Puerto Varas": "puerto-varas",
        "Castro": "castro",
        "Ancud": "ancud",
        "Chonchi": "chonchi",
        "Curaco de Vélez": "curaco-de-velez",
        "Dalcahue": "dalcahue",
        "Puqueldón": "puqueldon",
        "Queilén": "queilen",
        "Quellón": "quellon",
        "Quemchi": "quemchi",
        "Quinchao": "quinchao",
        "Osorno": "osorno",
        "Puerto Octay": "puerto-octay",
        "Purranque": "purranque",
        "Puyehue": "puyehue",
        "Río Negro": "rio-negro",
        "San Juan de la Costa": "san-juan-de-la-costa",
        "San Pablo": "san-pablo",
        "Chaitén": "chaiten",
        "Futaleufú": "futaleufu",
        "Hualaihué": "hualaihue",
        "Palena": "palena",
    },
    "aysen": {
        "Coihaique": "coihaique",
        "Lago Verde": "lago-verde",
        "Aisén": "aisen",
        "Cisnes": "cisnes",
        "Guaitecas": "guaitecas",
        "Cochrane": "cochrane",
        "O'Higgins": "ohiggins",
        "Tortel": "tortel",
        "Chile Chico": "chile-chico",
        "Río Ibáñez": "rio-ibanez",
    },
    "magallanes-y-antartica-chilena": {
        "Punta Arenas": "punta-arenas",
        "Laguna Blanca": "laguna-blanca",
        "Río Verde": "rio-verde",
        "San Gregorio": "san-gregorio",
        "Cabo de Hornos": "cabo-de-hornos",
        "Antártica": "antartica",
        "Porvenir": "porvenir",
        "Primavera": "primavera",
        "Timaukel": "timaukel",
        "Natales": "natales",
        "Torres del Paine": "torres-del-paine",
    },
    "metropolitana": {
        "Alhué": "alhue",
        "Buin": "buin",
        "Calera de Tango": "calera-de-tango",
        "Cerrillos": "cerrillos",
        "Cerro Navia": "cerro-navia",
        "Colina": "colina",
        "Conchalí": "conchali",
        "Curacaví": "curacavi",
        "El Bosque": "el-bosque",
        "El Monte": "el-monte",
        "Estación Central": "estacion-central",
        "Huechuraba": "huechuraba",
        "Independencia": "independencia",
        "Isla de Maipo": "isla-de-maipo",
        "La Cisterna": "la-cisterna",
        "La Florida": "la-florida",
        "La Granja": "la-granja",
        "La Pintana": "la-pintana",
        "La Reina": "la-reina",
        "Lampa": "lampa",
        "Las Condes": "las-condes",
        "Lo Barnechea": "lo-barnechea",
        "Lo Espejo": "lo-espejo",
        "Lo Prado": "lo-prado",
        "Macul": "macul",
        "Maipú": "maipu",
        "María Pinto": "maria-pinto",
        "Melipilla": "melipilla",
        "Ñuñoa": "nunoa",
        "Padre Hurtado": "padre-hurtado",
        "Paine": "paine",
        "Pedro Aguirre Cerda": "pedro-aguirre-cerda",
        "Peñaflor": "penaflor",
        "Peñalolén": "penalolen",
        "Pirque": "pirque",
        "Providencia": "providencia",
        "Pudahuel": "pudahuel",
        "Puente Alto": "puente-alto",
        "Quilicura": "quilicura",
        "Quinta Normal": "quinta-normal",
        "Recoleta": "recoleta",
        "Renca": "renca",
        "San Bernardo": "san-bernardo",
        "San Joaquín": "san-joaquin",
        "San José de Maipo": "san-jose-de-maipo",
        "San Miguel": "san-miguel",
        "San Pedro": "san-pedro",
        "San Ramón": "san-ramon",
        "Santiago": "santiago",
        "Talagante": "talagante",
        "Til Til": "til-til",
        "Vitacura": "vitacura",
    },
    "nuble": {
        "Chillán": "chillan",
        "Bulnes": "bulnes",
        "Chillán Viejo": "chillan-viejo",
        "El Carmen": "el-carmen",
        "Pemuco": "pemuco",
        "Pinto": "pinto",
        "Quillón": "quillon",
        "San Ignacio": "san-ignacio",
        "Yungay": "yungay",
        "Quirihue": "quirihue",
        "Cobquecura": "cobquecura",
        "Coelemu": "coelemu",
        "Ninhue": "ninhue",
        "Portezuelo": "portezuelo",
        "Ránquil": "ranquil",
        "Treguaco": "treguaco",
        "San Carlos": "san-carlos",
        "Coihueco": "coihueco",
        "Ñiquén": "niquen",
        "San Fabián": "san-fabian",
        "San Nicolás": "san-nicolas",
    },
}
